FROM golang:1.20-alpine

# Set working directory
WORKDIR /app

# Install required packages
RUN apk add --no-cache git gcc musl-dev && \
    go install github.com/cosmtrek/air@latest

# Copy go.mod and go.sum
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Install air for hot reloading
RUN go install github.com/cosmtrek/air@latest

# Copy air config
COPY .air.toml ./

# Command to run air for hot reloading
CMD ["air", "-c", ".air.toml"]