version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zione_api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - mysql
    environment:
      - APP_ENV=production
      - APP_PORT=8080
      - APP_HOST=0.0.0.0
      - APP_URL=https://api.zionechain.cfd
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ALLOWED_ORIGINS=https://zionechain.cfd
    networks:
      - zione_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  mysql:
    image: mysql:8.0
    container_name: zione_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - zione_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

networks:
  zione_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local 