version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: zione_api_test
    environment:
      - APP_ENV=testing
      - DB_HOST=mysql_test
      - DB_PORT=3306
      - DB_NAME=zione_test_db
      - DB_USER=zione_test_user
      - DB_PASSWORD=zione_test_password
      - JWT_SECRET=test_jwt_secret
    depends_on:
      - mysql_test
    networks:
      - zione_test_network
    volumes:
      - .:/app
    command: go test -v ./tests/...

  mysql_test:
    image: mysql:8.0
    container_name: zione_mysql_test
    environment:
      - MYSQL_ROOT_PASSWORD=root_test_password
      - MYSQL_DATABASE=zione_test_db
      - MYSQL_USER=zione_test_user
      - MYSQL_PASSWORD=zione_test_password
    tmpfs:
      - /var/lib/mysql
    networks:
      - zione_test_network

networks:
  zione_test_network:
    driver: bridge 